//! Backward compatibility of the checksummed SSTable format (G24).
//!
//! G24 changed the on-disk SSTable format: V3/V4 carry a 72-byte footer
//! with a metadata checksum where V1/V2 carried 64 bytes and none.
//! Reading yesterday's files is not a nice-to-have there; a table lark
//! can no longer open is the whole database gone, so it is data loss and
//! it is checked against real bytes rather than against a re-creation of
//! the old layout by the same code that changed it.
//!
//! The fixtures under `tests/fixtures/legacy_v1v2/` were written by the
//! pre-change tree (commit `d1ec2e7`), by running its own public
//! `SstFileWriter` and `Db`, and copied in byte for byte. Their trailing
//! magic is asserted here, so a fixture accidentally regenerated by the
//! current writer fails the test instead of quietly making it vacuous.

use std::fs;
use std::path::Path;

use lark_kv::{Db, IngestOptions, Options};
use tempfile::TempDir;

const FLAT_V1: &[u8] = include_bytes!("fixtures/legacy_v1v2/legacy_flat.sst");
const PARTITIONED_V2: &[u8] = include_bytes!("fixtures/legacy_v1v2/legacy_partitioned.sst");
const DB_MANIFEST: &[u8] = include_bytes!("fixtures/legacy_v1v2/legacy_db/MANIFEST");
const DB_TABLE: &[u8] = include_bytes!("fixtures/legacy_v1v2/legacy_db/sst/000029.sst");

/// "LARKSST\x01" and "LARKSST\x02" little-endian: the last eight bytes
/// of a V1 and a V2 table.
const MAGIC_V1_LE: [u8; 8] = [0x01, 0x54, 0x53, 0x53, 0x4b, 0x52, 0x41, 0x4c];
const MAGIC_V2_LE: [u8; 8] = [0x02, 0x54, 0x53, 0x53, 0x4b, 0x52, 0x41, 0x4c];

/// The same generator the fixture writer used.
fn entries(n: usize) -> Vec<(Vec<u8>, Vec<u8>)> {
    (0..n)
        .map(|i| {
            (
                format!("legacy_key_{i:06}").into_bytes(),
                format!("legacy_val_{i:06}_{}", "x".repeat(i % 37)).into_bytes(),
            )
        })
        .collect()
}

fn assert_magic(bytes: &[u8], want: [u8; 8], what: &str) {
    assert_eq!(
        &bytes[bytes.len() - 8..],
        &want,
        "{what} is not in the legacy format any more; the fixture was regenerated and this \
         test no longer proves compatibility",
    );
}

fn opts() -> Options {
    Options {
        write_buffer_size: 64 * 1024,
        ..Options::default()
    }
}

fn scan_all(db: &Db) -> Vec<(Vec<u8>, Vec<u8>)> {
    let mut it = db.iter();
    it.seek_to_first();
    let mut out = Vec::new();
    while it.valid() {
        out.push((
            it.key().expect("key").to_vec(),
            it.value().expect("value").to_vec(),
        ));
        it.next();
    }
    it.status().expect("iterator error");
    out
}

fn reverse_all(db: &Db) -> Vec<(Vec<u8>, Vec<u8>)> {
    let mut it = db.iter();
    it.seek_to_last();
    let mut out = Vec::new();
    while it.valid() {
        out.push((
            it.key().expect("key").to_vec(),
            it.value().expect("value").to_vec(),
        ));
        it.prev();
    }
    it.status().expect("iterator error");
    out.reverse();
    out
}

/// Ingest a real V1 (flat-index, 64-byte footer, no metadata checksum)
/// table written by the pre-change tree, then require every read surface
/// to serve it: point gets, a forward scan, a reverse scan, and misses.
#[test]
fn a_real_legacy_v1_table_is_still_read_after_the_format_change() {
    assert_magic(FLAT_V1, MAGIC_V1_LE, "legacy_flat.sst");
    let dir = TempDir::new().expect("tempdir");
    let sst = dir.path().join("legacy_flat.sst");
    fs::write(&sst, FLAT_V1).expect("write fixture");

    let db_dir = TempDir::new().expect("tempdir");
    let db = Db::open(db_dir.path(), opts()).expect("open");
    db.ingest_external_files(&[sst], IngestOptions::default())
        .expect("a V1 table must still ingest");

    let want = entries(200);
    for (k, v) in &want {
        assert_eq!(
            db.get(k).expect("get"),
            Some(v.clone()),
            "V1 table: {} did not come back",
            String::from_utf8_lossy(k),
        );
    }
    assert_eq!(db.get(b"legacy_key_999999").expect("get"), None);
    let mut sorted = want.clone();
    sorted.sort();
    assert_eq!(scan_all(&db), sorted, "V1 table: forward scan");
    assert_eq!(reverse_all(&db), sorted, "V1 table: reverse scan");
}

/// The same, for a real V2 partitioned-index table: its index leaves are
/// read through `read_index_leaf`, which is where the new per-leaf
/// checksum lives, so a leaf that carries no trailer must still parse.
#[test]
fn a_real_legacy_v2_partitioned_table_is_still_read_after_the_format_change() {
    assert_magic(PARTITIONED_V2, MAGIC_V2_LE, "legacy_partitioned.sst");
    let dir = TempDir::new().expect("tempdir");
    let sst = dir.path().join("legacy_partitioned.sst");
    fs::write(&sst, PARTITIONED_V2).expect("write fixture");

    let db_dir = TempDir::new().expect("tempdir");
    let db = Db::open(db_dir.path(), opts()).expect("open");
    db.ingest_external_files(&[sst], IngestOptions::default())
        .expect("a V2 partitioned table must still ingest");

    let want = entries(200);
    for (k, v) in &want {
        assert_eq!(
            db.get(k).expect("get"),
            Some(v.clone()),
            "V2 table: {} did not come back",
            String::from_utf8_lossy(k),
        );
    }
    let mut sorted = want.clone();
    sorted.sort();
    assert_eq!(scan_all(&db), sorted, "V2 partitioned table: forward scan");
    assert_eq!(
        reverse_all(&db),
        sorted,
        "V2 partitioned table: reverse scan"
    );
}

/// A whole database directory written by the pre-change tree, with all
/// 600 writes compacted into one V1 SSTable and an empty WAL, must open
/// and serve every one of them.
#[test]
fn a_whole_legacy_database_directory_still_opens_and_serves_every_key() {
    assert_magic(DB_TABLE, MAGIC_V1_LE, "the legacy database's SSTable");
    let root = TempDir::new().expect("tempdir");
    let db_dir = root.path().join("legacy_db");
    fs::create_dir_all(db_dir.join("sst")).expect("mkdir sst");
    fs::create_dir_all(db_dir.join("wal")).expect("mkdir wal");
    fs::write(db_dir.join("MANIFEST"), DB_MANIFEST).expect("write manifest");
    fs::write(db_dir.join("sst").join("000029.sst"), DB_TABLE).expect("write table");

    let db = Db::open(&db_dir, opts()).expect("a legacy database directory must still open");
    let want = entries(600);
    for (i, (k, v)) in want.iter().enumerate() {
        let got = db.get(k).expect("get");
        if i == 5 {
            assert_eq!(got, None, "legacy_key_000005 was deleted before the close");
        } else {
            assert_eq!(
                got,
                Some(v.clone()),
                "legacy database: {} did not come back",
                String::from_utf8_lossy(k),
            );
        }
    }
    let mut sorted: Vec<_> = want
        .into_iter()
        .enumerate()
        .filter(|(i, _)| *i != 5)
        .map(|(_, kv)| kv)
        .collect();
    sorted.sort();
    assert_eq!(scan_all(&db), sorted, "legacy database: forward scan");
    assert_eq!(reverse_all(&db), sorted, "legacy database: reverse scan");
}

/// A legacy table and a freshly written checksummed one have to live in
/// the same tree and be merged into each other. This overwrites half the
/// legacy keys, deletes some, adds new ones, and compacts, then requires
/// the result to be exactly what those writes imply.
///
/// Catches a merge path that mixes the two footer layouts up, and a
/// compaction that upgrades a table by reading it with the wrong region
/// bounds.
#[test]
fn a_legacy_table_and_a_checksummed_one_merge_without_losing_data() {
    let root = TempDir::new().expect("tempdir");
    let db_dir = root.path().join("legacy_db");
    fs::create_dir_all(db_dir.join("sst")).expect("mkdir sst");
    fs::create_dir_all(db_dir.join("wal")).expect("mkdir wal");
    fs::write(db_dir.join("MANIFEST"), DB_MANIFEST).expect("write manifest");
    fs::write(db_dir.join("sst").join("000029.sst"), DB_TABLE).expect("write table");

    let db = Db::open(&db_dir, opts()).expect("open");
    let base = entries(600);

    // Build the expected state alongside the writes rather than deriving
    // it afterwards, so the assertion is independent of the engine.
    let mut want: std::collections::BTreeMap<Vec<u8>, Vec<u8>> = base
        .iter()
        .enumerate()
        .filter(|(i, _)| *i != 5)
        .map(|(_, (k, v))| (k.clone(), v.clone()))
        .collect();

    for (i, (k, _)) in base.iter().enumerate() {
        if i % 2 == 0 && i != 5 {
            let v = format!("rewritten_{i:06}").into_bytes();
            db.put(k, &v).expect("put");
            want.insert(k.clone(), v);
        }
        if i % 7 == 3 {
            db.delete(k).expect("delete");
            want.remove(k);
        }
    }
    for i in 0..200usize {
        let k = format!("new_key_{i:06}").into_bytes();
        let v = format!("new_val_{i:06}").into_bytes();
        db.put(&k, &v).expect("put");
        want.insert(k, v);
    }
    db.compact_range(None, None).expect("compact_range");

    let expect: Vec<(Vec<u8>, Vec<u8>)> = want.into_iter().collect();
    assert_eq!(scan_all(&db), expect, "mixed-format merge: forward scan");
    assert_eq!(reverse_all(&db), expect, "mixed-format merge: reverse scan");
    for (k, v) in &expect {
        assert_eq!(
            db.get(k).expect("get"),
            Some(v.clone()),
            "mixed-format merge: {} did not come back",
            String::from_utf8_lossy(k),
        );
    }
    db.close().expect("close");
    drop(db);

    let magics = table_magics(&db_dir.join("sst"));
    let legacy = magics
        .iter()
        .filter(|m| **m == MAGIC_V1_LE || **m == MAGIC_V2_LE)
        .count();
    println!(
        "mixed-format merge: {} entries correct across {} table(s), {legacy} still legacy",
        expect.len(),
        magics.len(),
    );

    let db = Db::open(&db_dir, opts()).expect("reopen");
    assert_eq!(
        scan_all(&db),
        expect,
        "mixed-format merge: scan after reopen"
    );
}

fn table_magics(sst_dir: &Path) -> Vec<[u8; 8]> {
    let mut out = Vec::new();
    for entry in fs::read_dir(sst_dir).expect("read_dir").flatten() {
        let bytes = fs::read(entry.path()).expect("read");
        if bytes.len() >= 8 {
            let mut m = [0u8; 8];
            m.copy_from_slice(&bytes[bytes.len() - 8..]);
            out.push(m);
        }
    }
    out
}
